QUESTÃO 1: Crie dois NumPy Arrays unidimensionais de tamanho 8: um formado apenas por 1’s e outro formado por números aleatórios entre 0 e 9. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:
 Se a soma de todos os elementos do Array resultante for >= 40, remodele este NumPy Array para se tornar uma matriz com mais linhas do que colunas. Senão, remodele para que se torne uma matriz com mais colunas do que linhas.

In [2]:
import numpy as np

In [10]:
arr1 = np.ones(8)
arr2 = np.random.randint(0, 10, 8)

array_result = arr1 + arr2

if np.sum(array_result) >= 40:
    array_result = array_result.reshape([2,-1])

else:
    array_result = array_result.reshape([-1,2])

print(f'Array 1: {arr1}')
print()
print(f'Array 2: {arr2}')
print()
print(f'O resultado da matriz é: {array_result}')



Array 1: [1. 1. 1. 1. 1. 1. 1. 1.]

Array 2: [3 0 5 8 5 1 7 8]

O resultado da matriz é: [[4. 1. 6. 9.]
 [6. 2. 8. 9.]]


QUESTÃO 2: Mini Campo Minado:
a)Crie um NumPy Array 2x2 formado apenas por 0’s
b)Em seguida, adicione um número 1 em uma posição aleatória desta matriz;
c)Faça uma entrada de dados para solicitar o usuário que faça uma jogada (selecione
uma posição da matriz)
◦ Se ele selecionar todas as posições em que o número 1 não se encontra, mostre a
mensagem “Congratulations! You beat the game! :)”
◦ Senão, se dentro das 3 primeiras jogadas ele achar o número 1, mostre a
mensagem
◦ “Game Over! :( Try Again!”

In [11]:
matriz = np.zeros([2,2])

linha = np.random.randint(0, matriz.shape[0])
coluna = np.random.randint(0, matriz.shape[1])

matriz[linha, coluna] = 1

print(f'Posição sorteada: [{linha, {coluna}}]')
print(matriz)



Posição sorteada: [(0, {0})]
[[1. 0.]
 [0. 0.]]


QUESTÃO 3: Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas,
multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos.

In [14]:
matriz = np.random.randint(0, 10, [5,5])

soma_linhas = matriz.shape[0]
soma_colunas = matriz.shape[1]
linhas_por_colunas = soma_linhas * soma_colunas
paridade = 'par' if linhas_por_colunas % 2 == 0 else 'ímpar'

print(f'A quantidade de linhas é: {soma_linhas}')
print(f'A quantidade de colunas é: {soma_colunas}')
print(f'O total de elementos ao achatar é: {linhas_por_colunas}')
print(f'Esta matriz se tornaria um vetor unidimensional com número {paridade} de elementos.')



A quantidade de linhas é: 5
A quantidade de colunas é: 5
O total de elementos ao achatar é: 25
Esta matriz se tornaria um vetor unidimensional com número ímpar de elementos.


QUESTÃO 4: Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes)
a) Mostre o resultado da média de cada linha e cada coluna da matriz gerada
b) Apresente o maior valor das médias das linhas e também das colunas
c) Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em
seguida, mostre apenas os números que aparecem 2 vezes

In [19]:
np.random.seed(10)
matriz = np.random.randint(1, 51, [4, 4])

print('Matriz Gerada')
print(matriz)
print()

media_linhas = matriz.mean(axis=1)
media_colunas = matriz.mean(axis=0)
                    
maior_media_linhas = media_linhas.max()
maior_media_colunas = media_colunas.max()

print('a)')
print(f'Maior média entre as linhas: {maior_media_linhas}')
print()
print('b)')
print(f'Maior media entre as colunas: {maior_media_colunas}')

Matriz Gerada
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

a)
Maior média entre as linhas: 34.5

b)
Maior media entre as colunas: 33.75


QUESTÃO 5: Crie uma matriz de tamanho 3x3 formada apenas por zeros e outra também de
tamanho 3x3 formada apenas por uns. Some as duas matrizes elemento a elemento e
multiplique o resultado por um escalar de sua escolha. Por fim, remodele (reshape) a matriz resultante para um array unidimensional de 9 elementos.

In [20]:
matriz0 = np.zeros([3, 3])
matriz1 = np.ones([3, 3])

soma_matrizes = matriz0 + matriz1

resultado = soma_matrizes * 7

matriz1d = resultado.reshape(9)

print(f'Matriz de 0: {matriz0}')
print(f'Matriz 1: {matriz1}')
print()
print(f'Soma das matrizes: {soma_matrizes}')
print(f'Resultado multiplicado pelo escalar 7: {resultado}')
print(f'Matriz final: {matriz1d}')

Matriz de 0: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz 1: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Soma das matrizes: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Resultado multiplicado pelo escalar 7: [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
Matriz final: [7. 7. 7. 7. 7. 7. 7. 7. 7.]


QUESTÃO 6: Crie um NumPy Array unidimensional com os números de 10 a 30, espaçados de 2
em 2 usando arange. Mostre o maior valor do array e seu índice, o menor valor e seu índice, e a soma de todos os elementos.

In [26]:
arr = np.arange(10,31,2)

print(f'array: {arr}')

print(f'Maior valor do array: {arr.max()},\n Índice: {arr.argmax()}')
print(f'Menor valor do array: {arr.min()},\n Índice: {arr.argmin()}')
print()

print(f'Soma de todos os elementos: {arr.sum()}')

array: [10 12 14 16 18 20 22 24 26 28 30]
Maior valor do array: 30,
 Índice: 10
Menor valor do array: 10,
 Índice: 0

Soma de todos os elementos: 220


QUESTÃO 7: Crie dois NumPy Arrays unidimensionais de tamanho 5 com números aleatórios
entre 1 e 10 (use seed=7). Concatene os dois arrays em um terceiro e, transforme-o em uma matriz com 2 linhas e 5 colunas.

In [28]:
np.random.seed(7)

arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)

arr3 = np.concatenate((arr1, arr2))

matriz = arr3.reshape([2,5])

print(f'Array 1: {arr1}')
print(f'Array 2: {arr2}')
print()

print(f'Array Concatenado: {arr3}')

print(f'Matriz do Array concatenado: {matriz}')



Array 1: [ 5 10  7  4  4]
Array 2: [ 8  8 10  8  9]

Array Concatenado: [ 5 10  7  4  4  8  8 10  8  9]
Matriz do Array concatenado: [[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
